spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cq?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      database: 1
      timeout: 3000ms # 连接超时时间
      lettuce:
        pool:
          max-active: 20 # 最大连接数
          max-idle: 10   # 最大空闲连接
          min-idle: 5    # 最小空闲连接
          max-wait: 3000ms # 获取连接的最大等待时间


  security:
    user:
      name: admin
      password: admin

  mvc:
    static-path-pattern: /img/**
  web:
      resources:
        static-locations: file:${user.dir}/src/main/java/edu/cqie/cqdemo/img/

  # 邮件配置（使用QQ邮箱发送验证码）
  mail:
    host: smtp.qq.com
    username: 2686262955@qq.com          # 你的QQ邮箱
    password: xggtlqeegzggdfji
    port: 587
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# MyBatis Plus ??
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # ??????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ??SQL??
  global-config:
    db-config:
      id-type: auto # ????

# JWT ?????
jwt:
  secret: vue-spring-security-demo-1234567890abcdefghijklmn # ?????256????????
  expire-time: 720000 # ?????2??????
  token-header: Authorization # ?????
  token-prefix: Bearer # Token??

langchin4j:
  community:
    dashscope:
      model-name: qwen-max
      api-key: sk-67ce19f833ea430789b3a6d8d8e3e085

# 阿里云oss连接
aliyun:
  oss:
    endpoint: oss-cn-chengdu.aliyuncs.com          # 你的OSS地域节点
    accessKeyId: LTAI5tJc6t7sroYUuaAKBagq         # 替换为你的AccessKey ID
    accessKeySecret: Bcu4eFc5uwdonur3zWhS6zw76b1IEO # 替换为你的AccessKey Secret
    bucketName: cq-resource                       # 替换为你的Bucket名称
